### ISSUE TITLE
Use PySide6 and make the UI float over apps

### ISSUE THREAD

**Issue by SolsticeSpectrum** [LOUDO56/PyMacroRecord#20]
- It would be nice to have more fledged out UI, a list of macros (could be a simple file list)
- An ability of the window to float on top of other windows 
- Ability to change transparency
- Enable Mouse should stop mouse inputs from playing back, but it should record them anyway

I made a quick example of what it could look like
https://gist.github.com/SolsticeSpectrum/e6e2d91c8ffea536797579c3c79be9ac

I think the borderless should be kept, it can be done with regular border too but this looks nicer

**Comment by LOUDO56** [comment]
I'm not a big fan of the new UI because it's not a very friendly UI in my opinion, the core of PyMacroRecord is to just have 2 buttons so you can easely perform actions. Moreover, even if I liked it, it would be an hard task to redevelop everything from scratch. Tkinter does the job and I don't think it needs a new UI. Thank you for your suggestion though. If you want you still can clone or fork the repository to test it yourself.
