### ISSUE TITLE
Higher Mouse Polling Rate Causes Significant Delay in Macro Replay

### ISSUE THREAD

**Issue by Tesic-Nikola** [LOUDO56/PyMacroRecord#25]
### Bug Description:
When setting the mouse polling rate to a higher value (e.g., 1000 Hz), there is a noticeable delay in cursor movements that increases with the duration of recording.As the recording progresses, the delay in cursor movements becomes more pronounced, leading to inaccurate recordings.

### Steps to Reproduce:

1. Set the mouse polling rate to a value higher than 125 Hz
2. Begin recording a macro.
3. Record for more than 1 minute, ensuring to move the mouse frequently and click on various time-based items.

### Side Note:
Even when the polling rate is set to 125 Hz, there is a small but noticeable delay in cursor movements during recording.

**Comment by LOUDO56** [comment]
PyMacroRecord is a Python-based application, so my application may have problems with slowness. Also, the recordings can't be accurate, it's just a simulation of your movements, it records your movement at intervals, so if you speed up your mouse speed, you can get inaccurate recordings. If you want to avoid this problem, you can disable movement recording in the settings so that it only records your mouse click.
