### ISSUE TITLE
Mouse clicks are not being recorded during playback

### ISSUE THREAD

**Issue by CodeGiver01** [LOUDO56/PyMacroRecord#46]
**Describe the bug**
My mouse clicks are not registered when I record my macro for my Roblox client.
**To Reproduce**
Record the macro on the Roblox client while clicking the mouse and then play it back.
**Screenshots**

https://github.com/user-attachments/assets/f62d6181-d43e-40ed-a69f-5ad11535466f

**The OS**
![Screenshot (500)](https://github.com/user-attachments/assets/a3d2a76b-4018-4500-ab26-d5a87887c1a3)

**Additional context**
It may just be the Roblox client.

**Comment by CodeGiver01** [comment]
This is only the Roblox client.

**Comment by LOUDO56** [comment]
It's probably because of pynput (the module to move and make the mouse click) that does this and... I can't really do much about it :/
But you can solve this by putting the roblox client in windows mode, record your macro then at the end you click outside the window.
Hope it can solve your problem


https://github.com/user-attachments/assets/c1f833bf-74a4-489f-8cff-09c155e47007

**Comment by CodeGiver01** [comment]
Really late reply but thank you!
